// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserFullInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserID           string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	Account          string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account"`
	PhoneNumber      string                 `protobuf:"bytes,4,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	AreaCode         string                 `protobuf:"bytes,5,opt,name=areaCode,proto3" json:"areaCode"`
	Email            string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email"`
	Nickname         string                 `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname"`
	FaceURL          string                 `protobuf:"bytes,8,opt,name=faceURL,proto3" json:"faceURL"`
	Gender           int32                  `protobuf:"varint,9,opt,name=gender,proto3" json:"gender"`
	Level            int32                  `protobuf:"varint,10,opt,name=level,proto3" json:"level"`
	Birth            int64                  `protobuf:"varint,11,opt,name=birth,proto3" json:"birth"`
	AllowAddFriend   int32                  `protobuf:"varint,12,opt,name=allowAddFriend,proto3" json:"allowAddFriend"`
	AllowBeep        int32                  `protobuf:"varint,13,opt,name=allowBeep,proto3" json:"allowBeep"`
	AllowVibration   int32                  `protobuf:"varint,14,opt,name=allowVibration,proto3" json:"allowVibration"`
	GlobalRecvMsgOpt int32                  `protobuf:"varint,15,opt,name=globalRecvMsgOpt,proto3" json:"globalRecvMsgOpt"`
	RegisterType     int32                  `protobuf:"varint,16,opt,name=registerType,proto3" json:"registerType"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserFullInfo) Reset() {
	*x = UserFullInfo{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFullInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFullInfo) ProtoMessage() {}

func (x *UserFullInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFullInfo.ProtoReflect.Descriptor instead.
func (*UserFullInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *UserFullInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserFullInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserFullInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserFullInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserFullInfo) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *UserFullInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserFullInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserFullInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *UserFullInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserFullInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserFullInfo) GetBirth() int64 {
	if x != nil {
		return x.Birth
	}
	return 0
}

func (x *UserFullInfo) GetAllowAddFriend() int32 {
	if x != nil {
		return x.AllowAddFriend
	}
	return 0
}

func (x *UserFullInfo) GetAllowBeep() int32 {
	if x != nil {
		return x.AllowBeep
	}
	return 0
}

func (x *UserFullInfo) GetAllowVibration() int32 {
	if x != nil {
		return x.AllowVibration
	}
	return 0
}

func (x *UserFullInfo) GetGlobalRecvMsgOpt() int32 {
	if x != nil {
		return x.GlobalRecvMsgOpt
	}
	return 0
}

func (x *UserFullInfo) GetRegisterType() int32 {
	if x != nil {
		return x.RegisterType
	}
	return 0
}

type UserPublicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname"`
	FaceURL       string                 `protobuf:"bytes,5,opt,name=faceURL,proto3" json:"faceURL"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender"`
	Level         int32                  `protobuf:"varint,7,opt,name=level,proto3" json:"level"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPublicInfo) Reset() {
	*x = UserPublicInfo{}
	mi := &file_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPublicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPublicInfo) ProtoMessage() {}

func (x *UserPublicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPublicInfo.ProtoReflect.Descriptor instead.
func (*UserPublicInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *UserPublicInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserPublicInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserPublicInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserPublicInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserPublicInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *UserPublicInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserPublicInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type UserIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email"`
	AreaCode      string                 `protobuf:"bytes,2,opt,name=areaCode,proto3" json:"areaCode"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	DeviceID      string                 `protobuf:"bytes,4,opt,name=deviceID,proto3" json:"deviceID"`
	Platform      int32                  `protobuf:"varint,5,opt,name=platform,proto3" json:"platform"`
	Account       string                 `protobuf:"bytes,6,opt,name=account,proto3" json:"account"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *UserIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserIdentity) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *UserIdentity) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserIdentity) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *UserIdentity) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *UserIdentity) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type AppletInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	AppID         string                 `protobuf:"bytes,3,opt,name=appID,proto3" json:"appID"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url"`
	Md5           string                 `protobuf:"bytes,6,opt,name=md5,proto3" json:"md5"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version"`
	Priority      uint32                 `protobuf:"varint,9,opt,name=priority,proto3" json:"priority"`
	Status        uint32                 `protobuf:"varint,10,opt,name=status,proto3" json:"status"`
	CreateTime    int64                  `protobuf:"varint,11,opt,name=createTime,proto3" json:"createTime"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppletInfo) Reset() {
	*x = AppletInfo{}
	mi := &file_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppletInfo) ProtoMessage() {}

func (x *AppletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppletInfo.ProtoReflect.Descriptor instead.
func (*AppletInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *AppletInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppletInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppletInfo) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *AppletInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AppletInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AppletInfo) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *AppletInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AppletInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppletInfo) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AppletInfo) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AppletInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type LogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Platform      int32                  `protobuf:"varint,2,opt,name=platform,proto3" json:"platform"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname"`
	LogID         string                 `protobuf:"bytes,6,opt,name=logID,proto3" json:"logID"`
	Filename      string                 `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename"`
	SystemType    string                 `protobuf:"bytes,8,opt,name=systemType,proto3" json:"systemType"`
	Ex            string                 `protobuf:"bytes,9,opt,name=ex,proto3" json:"ex"`
	Version       string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInfo) Reset() {
	*x = LogInfo{}
	mi := &file_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInfo) ProtoMessage() {}

func (x *LogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInfo.ProtoReflect.Descriptor instead.
func (*LogInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *LogInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *LogInfo) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *LogInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LogInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *LogInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LogInfo) GetLogID() string {
	if x != nil {
		return x.LogID
	}
	return ""
}

func (x *LogInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *LogInfo) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *LogInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *LogInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\x12openim.chat.common\"\xe8\x03\n" +
	"\fUserFullInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12 \n" +
	"\vphoneNumber\x18\x04 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bareaCode\x18\x05 \x01(\tR\bareaCode\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\a \x01(\tR\bnickname\x12\x18\n" +
	"\afaceURL\x18\b \x01(\tR\afaceURL\x12\x16\n" +
	"\x06gender\x18\t \x01(\x05R\x06gender\x12\x14\n" +
	"\x05level\x18\n" +
	" \x01(\x05R\x05level\x12\x14\n" +
	"\x05birth\x18\v \x01(\x03R\x05birth\x12&\n" +
	"\x0eallowAddFriend\x18\f \x01(\x05R\x0eallowAddFriend\x12\x1c\n" +
	"\tallowBeep\x18\r \x01(\x05R\tallowBeep\x12&\n" +
	"\x0eallowVibration\x18\x0e \x01(\x05R\x0eallowVibration\x12*\n" +
	"\x10globalRecvMsgOpt\x18\x0f \x01(\x05R\x10globalRecvMsgOpt\x12\"\n" +
	"\fregisterType\x18\x10 \x01(\x05R\fregisterType\"\xbc\x01\n" +
	"\x0eUserPublicInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x18\n" +
	"\afaceURL\x18\x05 \x01(\tR\afaceURL\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\"\xb4\x01\n" +
	"\fUserIdentity\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bareaCode\x18\x02 \x01(\tR\bareaCode\x12 \n" +
	"\vphoneNumber\x18\x03 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bdeviceID\x18\x04 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\x05R\bplatform\x12\x18\n" +
	"\aaccount\x18\x06 \x01(\tR\aaccount\"\x80\x02\n" +
	"\n" +
	"AppletInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05appID\x18\x03 \x01(\tR\x05appID\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x10\n" +
	"\x03md5\x18\x06 \x01(\tR\x03md5\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12\x1a\n" +
	"\bpriority\x18\t \x01(\rR\bpriority\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\rR\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\v \x01(\x03R\n" +
	"createTime\"\x87\x02\n" +
	"\aLogInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\x05R\bplatform\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x14\n" +
	"\x05logID\x18\x06 \x01(\tR\x05logID\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\x12\x1e\n" +
	"\n" +
	"systemType\x18\b \x01(\tR\n" +
	"systemType\x12\x0e\n" +
	"\x02ex\x18\t \x01(\tR\x02ex\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversionB/Z-github.com/openimsdk/chat/pkg/protocol/commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_common_proto_goTypes = []any{
	(*UserFullInfo)(nil),   // 0: openim.chat.common.UserFullInfo
	(*UserPublicInfo)(nil), // 1: openim.chat.common.UserPublicInfo
	(*UserIdentity)(nil),   // 2: openim.chat.common.UserIdentity
	(*AppletInfo)(nil),     // 3: openim.chat.common.AppletInfo
	(*LogInfo)(nil),        // 4: openim.chat.common.LogInfo
}
var file_common_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
