rpc:
  # The IP address where this RPC service registers itself; if left blank, it defaults to the internal network IP
  registerIP: ''
  # IP address that the RPC service listens on; setting to 0.0.0.0 listens on both internal and external IPs. If left blank, it automatically uses the internal network IP
  listenIP: 0.0.0.0
  # List of ports that the RPC service listens on; configuring multiple ports will launch multiple instances.
  ports: [ 30300 ]

verifyCode:
  validTime: 300
  validCount: 5
  uintTime: 86400
  maxCount: 10
  superCode: "666666"
  len: 6
  phone:
    use: "superCode"  # superCode: user superCode; ali: use ali verify code;
    ali:
      endpoint: ""
      accessKeyId: ""
      accessKeySecret: ""
      signName: ""
      verificationCodeTemplateCode: ""
  mail:
    use: "superCode"  # superCode: user superCode; mail: use mail verify code;
    title: ""
    senderMail: ""
    senderAuthorizationCode: ""
    smtpAddr: ""
    smtpPort:

liveKit:
  url: "ws://127.0.0.1:7880" # LIVEKIT_URL, LiveKit server address and port
  key: "APIGPW3gnFTzqHH"
  secret: "23ztfSqsfQ8hKkHzHTl3Z4bvaxro0snjk5jwbp5p6Q3"

allowRegister: true
