rpc:
  # The IP address where this RPC service registers itself; if left blank, it defaults to the internal network IP
  registerIP: ''
  # IP address that the RPC service listens on; setting to 0.0.0.0 listens on both internal and external IPs. If left blank, it automatically uses the internal network IP
  listenIP: 0.0.0.0
  # List of ports that the RPC service listens on; configuring multiple ports will launch multiple instances.
  ports: [ 30400 ]

# Model request timeout. Unit: s
timeout: 20
