# Copyright © 2023 OpenIM. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: OpenIM Chat Start Execute Scripts

on: 
    push:
      branches:
          - main
      paths-ignore:
          - "docs/**"
          - "README.md"
          - "README_zh-CN.md"
          - "CONTRIBUTING.md"
    pull_request:
      branches:
          - main
      paths-ignore:
          - "README.md"
          - "README_zh-CN.md"
          - "CONTRIBUTING.md"
          - "docs/**"

jobs:
  execute-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Chat
      run: |
        sudo make build
        sudo chmod +x ./scripts/build_all_service.sh
        sudo ./scripts/build_all_service.sh
      shell: bash

    - name: deploy all services
      run: |
        git clone https://github.com/openimsdk/open-im-server.git
        cd open-im-server
        sudo make init
        sudo docker compose up -d
        sudo sleep 30

        sudo make start
        sudo make check

        sudo cat logs/openIM.log 2>/dev/null
        echo "pwd = $(pwd)"
        cd ..
        ls -al && pwd
      shell: bash
      continue-on-error: true

    - name: start mysql
      run: |
        docker run -d \
          --name mysql4 \
          -p 13306:3306 \
          -p 3306:33060 \
          -v "$(pwd)/components/mysql/data:/var/lib/mysql" \
          -v "/etc/localtime:/etc/localtime" \
          -e MYSQL_ROOT_PASSWORD="openIM123" \
          --restart always \
          mysql:5.7
    - name: start all services
      run: |
        sudo cp ./config/config.yaml.template ./config/config.yaml
        sudo make start
      shell: bash

    - name: Check all services
      run: |
        sudo make check
      shell: bash

    - name: Stop chat
      run: |
        sudo make stop

    - name: Reinstall chat
      run: |
        sudo make install

    - name: Print openIM.log
      run: |
        ls -al && echo "pwd = $(pwd)"
        sudo cat ./logs/* 2>/dev/null
        sudo cat ./logs/* 2>/dev/null >> "$GITHUB_OUTPUT"
      shell: bash
      continue-on-error: true
